/********************************************************************
* LucasDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error LucasDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableLucasDict();
extern void G__cpp_setup_inheritanceLucasDict();
extern void G__cpp_setup_typetableLucasDict();
extern void G__cpp_setup_memvarLucasDict();
extern void G__cpp_setup_globalLucasDict();
extern void G__cpp_setup_memfuncLucasDict();
extern void G__cpp_setup_funcLucasDict();
extern void G__set_cpp_environmentLucasDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Track_t.hh"
#include "Hit_t.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LucasDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__LucasDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LucasDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__LucasDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LucasDictLN_Track_t;
extern G__linked_taginfo G__LucasDictLN_Hit_t;
extern G__linked_taginfo G__LucasDictLN_vectorlEHit_tcOallocatorlEHit_tgRsPgR;
extern G__linked_taginfo G__LucasDictLN_vectorlEHit_tcOallocatorlEHit_tgRsPgRcLcLiterator;
extern G__linked_taginfo G__LucasDictLN_reverse_iteratorlEvectorlEHit_tcOallocatorlEHit_tgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LucasDictLN_vectorlETrack_tcOallocatorlETrack_tgRsPgR;
extern G__linked_taginfo G__LucasDictLN_vectorlETrack_tcOallocatorlETrack_tgRsPgRcLcLiterator;
extern G__linked_taginfo G__LucasDictLN_reverse_iteratorlEvectorlETrack_tcOallocatorlETrack_tgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef vector<Hit_t,allocator<Hit_t> > G__vectorlEHit_tcOallocatorlEHit_tgRsPgR;
typedef vector<Track_t,allocator<Track_t> > G__vectorlETrack_tcOallocatorlETrack_tgRsPgR;
